# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.speed_field = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speed_field.setObjectName("speed_field")
        self.horizontalLayout.addWidget(self.speed_field)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.distance_field = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.distance_field.setObjectName("distance_field")
        self.horizontalLayout_2.addWidget(self.distance_field)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.vd_field = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.vd_field.setObjectName("vd_field")
        self.horizontalLayout_3.addWidget(self.vd_field)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.od_field = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.od_field.setObjectName("od_field")
        self.horizontalLayout_4.addWidget(self.od_field)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setMinimumSize(QtCore.QSize(36, 70))
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout_3.addWidget(self.load_btn)
        self.save_vtn = QtWidgets.QPushButton(self.centralwidget)
        self.save_vtn.setMinimumSize(QtCore.QSize(0, 70))
        self.save_vtn.setObjectName("save_vtn")
        self.verticalLayout_3.addWidget(self.save_vtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(92)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setMinimumSectionSize(24)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.table.verticalHeader().setMinimumSectionSize(30)
        self.verticalLayout_2.addWidget(self.table)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.start_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn_2.setMinimumSize(QtCore.QSize(0, 90))
        self.start_btn_2.setObjectName("start_btn_2")
        self.horizontalLayout_6.addWidget(self.start_btn_2)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setMinimumSize(QtCore.QSize(0, 90))
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_6.addWidget(self.start_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MoonLight Laboratory"))
        self.label.setText(_translate("MainWindow", "Скорость каретки"))
        self.label_2.setText(_translate("MainWindow", "Расстояние"))
        self.label_3.setText(_translate("MainWindow", "D Волокна"))
        self.label_4.setText(_translate("MainWindow", "D Оболочки "))
        self.load_btn.setText(_translate("MainWindow", "Загрузить"))
        self.save_vtn.setText(_translate("MainWindow", "Сохранить"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Набор"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Прочность"))
        self.start_btn_2.setText(_translate("MainWindow", "КАЛИБРОВКА"))
        self.start_btn.setText(_translate("MainWindow", "ЗАПУСК"))

